global:
  scrape_interval:     120s 
  evaluation_interval: 120s 
  external_labels:
      monitor: 'my-project'

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 120s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'blog-post-api'
    scrape_interval: 10s
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:5001']
  - job_name: 'review-api'
    scrape_interval: 10s
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:5003']
  - job_name: 'pushgateway'
    scrape_interval: 10s
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:9091']