{
 "title": "Crash Course IPC - Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Request Review Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SQS Message Latency (95th percentile)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_sqs_messages_handling{exported_job=\"request-review-processor\",quantile=\"0.95\"}",
     "legendFormat": "{{action}}"
    }
   ]
  },
  { "title": "Review API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Average latency per endpoint",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (endpoint) (application_request_timer{service=\"Review.Api\"})",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  { "title": "Blog Post API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Average latency per endpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (endpoint) (application_request_timer{service=\"BlogPost.Api\"})",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Count errors (per min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(increase(application_sql_errors{service=\"BlogPost.Api\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}